// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"aws.accessKeyId": {
			Default:     "",
			Description: "aws.accessKeyId is the amazon access key id",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.region": {
			Default:     "",
			Description: "aws.region is the region where the stream is hosted",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.secretAccessKey": {
			Default:     "",
			Description: "aws.secretAccessKey is the amazon secret access key",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.url": {
			Default:     "",
			Description: "aws.url is the URL for endpoint override - testing/dry-run only",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"partitionKeyTemplate": {
			Default:     "",
			Description: "partitionKeyTemplate accepts a go template as an argument, with the record being written as the main data context. If an empty template is passed, the partition key will adopt the record key string value. If the record key string exceeds 256 it will be trimmed down from start to fit the partition key size",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"streamARN": {
			Default:     "",
			Description: "streamARN is the Kinesis stream's Amazon Resource Name",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"streamARNTemplate": {
			Default:     "",
			Description: "streamARNTemplate allows the destination to use a custom go template to parse the streamARN. The template will be given an sdk.Record as the main data context.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"streamName": {
			Default:     "",
			Description: "streamName is the name of the Kinesis Data Stream",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"useMultiStreamMode": {
			Default:     "false",
			Description: "useMultiStreamMode allows the destination to write to multiple streams. If set to true, by default the destination will use the streamARN from the opencdc.collection metadata field. If no collection is found, the destination will use the StreamARN parameter as the last resort. Use StreamARNTemplate to customise how the streamARN is parsed from the record.",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
	}
}
