// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package destination

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigAutoCreateStreams    = "auto.create.streams"
	ConfigAwsAccessKeyId       = "aws.accessKeyId"
	ConfigAwsRegion            = "aws.region"
	ConfigAwsSecretAccessKey   = "aws.secretAccessKey"
	ConfigAwsUrl               = "aws.url"
	ConfigPartitionKeyTemplate = "partitionKeyTemplate"
	ConfigStreamName           = "streamName"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigAutoCreateStreams: {
			Default:     "true",
			Description: "AutoCreateStreams makes the destination create a new stream if it does\nnot exist when writing records.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		ConfigAwsAccessKeyId: {
			Default:     "",
			Description: "AWSAccessKeyID is the amazon access key id",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsRegion: {
			Default:     "",
			Description: "AWSRegion is the region where the stream is hosted",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsSecretAccessKey: {
			Default:     "",
			Description: "AWSSecretAccessKey is the amazon secret access key",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigAwsUrl: {
			Default:     "",
			Description: "AWSURL is the URL for endpoint override - testing/dry-run only",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigPartitionKeyTemplate: {
			Default:     "",
			Description: "PartitionKeyTemplate accepts a go template as an argument, with the\nrecord being written as the main data context. If an empty template is\npassed, the partition key will adopt the record key string value. If the\nrecord key string exceeds 256 it will be trimmed down from start to fit\nthe partition key size",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigStreamName: {
			Default:     "{{ index .Metadata \"opencdc.collection\" }}",
			Description: "StreamName is the name of the Kinesis Data Stream. It can contain a\n[Go template](https://pkg.go.dev/text/template) that will be executed\nfor each record to determine the stream name. By default, the stream\nname is the value of the `opencdc.collection` metadata field.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
