// Copyright © 2024 Meroxa, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package source

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"aws.accessKeyId": {
			Default:     "",
			Description: "amazon access key id",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.region": {
			Default:     "",
			Description: "aws.region is the region where the stream is hosted",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.secretAccessKey": {
			Default:     "",
			Description: "amazon secret access key",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"aws.url": {
			Default:     "",
			Description: "URL for endpoint override - testing/dry-run only",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
		"startFromLatest": {
			Default:     "",
			Description: "startFromLatest defaults to false. When true, sets the iterator type to LATEST (iterates from the point that the connection begins). when false, sets the iterator type to TRIM_HORIZON (iterates from the oldest record in the shard).",
			Type:        sdk.ParameterTypeBool,
			Validations: []sdk.Validation{},
		},
		"streamARN": {
			Default:     "",
			Description: "streamARN is the Kinesis stream's Amazon Resource Name",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationRequired{},
			},
		},
		"streamName": {
			Default:     "",
			Description: "streamName is the name of the Kinesis Data Stream",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{},
		},
	}
}
